api:
  port: 3000
db:
  port: 6379
  id: 0
settings:
  skills:
    tier_1: 3
    tier_2: 6
    tier_3: 8
  jobs:
    service_fee: 10
    success_fee_brackets:
      bracket_0: 0
      bracket_1: 3000
      bracket_2: 8000
      bracket_3: 20000
      bracket_4: 50000
    success_fee_percentages:
      percentage_0: 50
      percentage_1: 35
      percentage_2: 25
      percentage_3: 20
      percentage_4: 10
    highlight_prices:
      sticky:
        7_days: 49
        14_days: 69
        30_days: 99
      highlight_frame:
        default: 79
  char_limits:
    profile:
      username: 15
      title: 15
      bio: 1000
contract_addresses:
  membership_nft: 0x610907faEb17Db469fDFcd2b7355c2094cCD1bAF
  job_payments: 0x610907faEb17Db469fDFcd2b7355c2094cCD1bAF
network:
  1453:
    name: devm
    rpc_url: https://decoded.wtf
